[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[project]
name = "sam3-service"
version = "0.0.0"
description = "ALCF Inference Server for SAM3 (Segment Anything Model 3)"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Misha Salim"}
]
dependencies = [
    "rich",
    "typer",
    "fastapi",
    "uvicorn[standard]",
    "numpy",
    "Pillow",
    "smart_open",
    "transformers",
    "torch",
    "torchvision",
    "matplotlib",
    "requests",
    "tifffile",
    "globus-compute-endpoint",
    "globus-compute-sdk",
]

[project.scripts]
sam3-service = "sam3_service.client:cli"

[dependency-groups]
dev = [
    "ruff",
]
