[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[project]
name = "sam3server"
version = "0.0.0"
description = "ALCF Inference Server for SAM3 (Segment Anything Model 3)"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Misha Salim"}
]
dependencies = [
    "sam3[dev,notebooks,train]",
    "rich",
    "typer",
    "fastapi",
    "uvicorn[standard]",
    "numpy",
    "Pillow",
    "smart_open",
    "setuptools<82", # yes, sam3 actually depends on this
    "transformers",
    "webdataset",
]

[dependency-groups]
dev = [
    "ruff",
]

[tool.uv.sources]
sam3 = { git = "https://github.com/facebookresearch/sam3" }